# Практ. робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [3]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [4]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [3]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [4]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x4eeebd8
byteorder:  little
byteswap:  False
type: int32


In [5]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [8]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.05210639 0.82229199 0.58740376]
 [0.1544309  0.53132478 0.30475583]
 [0.97577182 0.59893664 0.06352883]]


In [9]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [10]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.05210639 0.82229199 0.58740376]
 [0.1544309  0.53132478 0.30475583]
 [0.97577182 0.59893664 0.06352883]]
...
float64
(3, 3)
3
2
9
8
72


In [11]:
arr.__sizeof__()

128

### ЗАВДАННЯ 1

In [14]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = np.array([[1.1, 2.2, 3.3, 4], [5.5, 6.6, 7, 8.8], [9.9, 10, 11.1, 12.2]])
np.info(arr1_1[0])

class:  ndarray
shape:  (4,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x72ac4f0
byteorder:  little
byteswap:  False
type: float64


In [15]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = ['Привет','Как дела?','Я','Ты','Он']
print(arr1_2)

['Привет', 'Как дела?', 'Я', 'Ты', 'Он']


In [17]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.random.uniform(1.0,10.1,size=(3,4))
print(arr1_3)

[[4.144395   1.55154184 9.09596737 1.86616114]
 [2.29583579 8.33782753 9.76021461 4.69310238]
 [1.77015161 6.99549533 6.114029   8.77226758]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [22]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)
print(arr.dtype)

[0 1 2 3 4 5 6 7 8 9]
int32


In [23]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [24]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [25]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [29]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.full((3,1,3),False)
print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


In [32]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape(3,3)
print(arr2_2)
arr2_2 = arr2_2.astype('int64')
print(arr2_2)

[[False False False]
 [False False False]
 [False False False]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [35]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = np.arange(10, 21, 2).reshape(2,3)
print(arr2_3)

[[10 12 14]
 [16 18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [71]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [72]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[17 27 11 15]
 [43 13 32 15]
 [27 29 34 40]
 [37 12 21 46]]


In [73]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, 2]
print(el)

32


In [74]:
# отримати значення останнього рядка
vect = arr[2]
print(vect)

[27 29 34 40]


In [75]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[17 27 11 15]
 [43 13 32 15]]


In [76]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[27 11]
 [13 32]
 [29 34]
 [12 21]]


In [77]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[17 27 11 15]
 [27 29 34 40]]


In [78]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[27 43 32 27 29 34 40 37 21 46]


### ЗАВДАННЯ 3

In [90]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 = np.random.randint(10,100,size=(4,5))
print(arr3_1)


[[61 43 93 82 63]
 [31 28 16 33 30]
 [68 11 51 10 83]
 [50 80 30 64 85]]


In [98]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1][2]
print(el3_2)

16


In [92]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1]
print(vect3_3)

[31 28 16 33 30]


In [93]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[:, 2]
print(vect3_4)

[93 16 51 30]


In [94]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[1:3, 1:3]
print(mat3_5)

[[28 16]
 [11 51]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [ ]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

In [ ]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

In [ ]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

In [ ]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

In [ ]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

In [ ]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

### ЗАВАДАННЯ 4

In [96]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.random.randint(100,200,size=(6,6))
print(mat4_1)

[[110 183 112 129 145 198]
 [167 143 129 126 168 104]
 [179 176 156 171 164 123]
 [137 140 104 175 108 173]
 [146 178 193 166 108 181]
 [162 194 167 185 115 160]]


In [97]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[110 143 156 175 108 160]


In [99]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[110 167 179 137 146 162]
 [183 143 176 140 178 194]
 [112 129 156 104 193 167]
 [129 126 171 175 166 185]
 [145 168 164 108 108 115]
 [198 104 123 173 181 160]]


In [101]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)
print(inv4_4)

[[-0.0122765   0.05380984 -0.06873317  0.00408643 -0.01257417  0.04286047]
 [ 0.00798205  0.00247753 -0.01155024 -0.01430603 -0.01750856  0.03266602]
 [-0.00237416 -0.01184531  0.01935207 -0.00525207  0.01981458 -0.02097587]
 [-0.0010067  -0.03945562  0.05157067  0.00945792  0.00280172 -0.02614883]
 [ 0.00725902 -0.02029846  0.0401475   0.00045749  0.00697483 -0.03503737]
 [ 0.00117633  0.01508715 -0.02508633  0.00742586  0.00502637  0.00055748]]


## 5. Операції над масивами

### ПРИКЛАДИ

In [ ]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [ ]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
...

In [ ]:
# матриця 3х4 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

In [ ]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

In [ ]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

In [ ]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

In [ ]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

In [ ]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

In [ ]:
# поелементний поділ
K = N / M
print(K)

In [ ]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

In [ ]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

In [ ]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

In [ ]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

In [ ]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

In [ ]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

In [ ]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

### ЗАВДАННЯ 5

In [103]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.randint(0,100,size=(3,4))
print(mat5_1)
sum_mat5_1 = np.sum(mat5_1, axis=1)
print(sum_mat5_1)

[[89 94 39 28]
 [46 87 53 58]
 [80 76 41 57]]
[250 244 254]


In [104]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = np.min(mat5_1)
print(min_mat5_1)

28


In [105]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = mat5_1+100
print(mat5_3)

[[189 194 139 128]
 [146 187 153 158]
 [180 176 141 157]]


In [108]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
diag5_4 = np.diag(mat5_3)
mat5_4 = np.dot(diag5_4, mat5_1 )
print(mat5_4)

[36703 44751 23063 24175]


In [135]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = np.array([mat5_3[0],mat5_3[1],mat5_3[2],mat5_4])
print(mat5_5)
np.linalg.matrix_rank(mat5_5)

[[  189   194   139   128]
 [  146   187   153   158]
 [  180   176   141   157]
 [36703 44751 23063 24175]]


4